### ISSUE TITLE
Why no provide center function ?

### ISSUE THREAD

**Issue by thiphariel** [JasonSanford/geojson-google-maps#25]
Hi.

I know there is an issue about this (#14) but you closed it without explain. This function is really useful in some case and I don't know why you reject it.  Any good reason ?

Thanks

**Comment by JasonSanford** [comment]
Hi thco, that was closed a number of years ago, so I can't remember exactly why I decided to close it but a few things that come to mind are:
1. There was no example usage of the new functionality.
2. The updated code wasn't sent in a pull request where it is easy to see exactly what changed. Pull requests also allow users to talk about proposed code changes easily.
3. I'm not sure the code changes are necessary. A user could more easily add `getCenter` and `getBounds` methods to the geometries' prototype.

I should have stated one or more of these when closing the above issue, so that's my fault. Still, I don't think something like this should be added.

**Comment by thiphariel** [comment]
Ok. I understand, I guess, it's really better to propose PR than hard readable code like this :)

Since few hours now, I tried this providedd code, and yeah, it's not very complient ... You right, maybe it's better to extend geometries prototype, or make some custom function that will read coordinates and fit map bounds with them.

Thanks for those informations !

I close :)

**Comment by JasonSanford** [comment]
:+1:
